### PR TITLE
Grammar correction

### PR DESCRIPTION
**Pull request by JasonAHeron**
"it's" can not be used like this. Changing to "the"
Cheers

### CODE REVIEW

**Comment by xori** [comment]
I agree, but could I not change it to its'?

> In the above example, we got out our fancy die from its' box.

**Comment by yet-another-account** [comment]
Or, you can use `its`, which is possessive.

**Comment by austinvuong** [comment]
_Its_ is the possessive form of _it_. _Its'_ is not valid English for [historic reasons](https://english.stackexchange.com/a/68653).

**Comment by xori** [comment]
You are correct. I don't know why I kept the apostrophe.

**Pull request merged**
